# Generated by Django 4.2.11 on 2024-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userID',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsecomment',
            name='respondedCommentID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responsecomment',
            name='responderID',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
