# Generated by Django 4.2.11 on 2024-04-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_comment_userid_responsecomment_respondedcommentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecomment',
            name='commentID',
        ),
    ]
