# Generated by Django 4.2.11 on 2024-04-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_remove_responsecomment_commentid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='respondedCommentID',
            field=models.BigIntegerField(default=-1),
            preserve_default=False,
        ),
    ]
